version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-app:
    build:
      context: .  # 현재 디렉토리에서 빌드
      dockerfile: Dockerfile  # Dockerfile을 사용하여 빌드
    image: chani999/re_book:latest
    container_name: spring-app
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://re-book-db.cl0qk0k6q3ee.ap-northeast-2.rds.amazonaws.com:3306/wwww
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    #제발.ㅏㅣㅗ